version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 20000token
  - 20000000000000000000000sao
- name: bob
  coins:
  - 10000token
  - 1000000000000000000000sao
faucet:
  name: bob
  coins:
  - 5token
  - 10000000sao
  host: 0.0.0.0:4500
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    node:
      params:
        block_reward: 
            amount: "10000000"
            denom: "sao"
    staking:
      params:
        bond_denom: "sao"
validators:
- name: alice
  bonded: 100000000sao
