version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 20000000000000000000000sao
- name: bob
  coins:
  - 1000000000000000000000sao
faucet:
  name: bob
  coins:
  - 10000000sao
  host: 0.0.0.0:4500
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    node:
      params:
        block_reward: 
            amount: "10000000"
            denom: "sao"
    staking:
      params:
        bond_denom: "sao"
    crisis:
      constant_fee:
        amount: "1000"
        denom: "sao"
    gov:
      deposit_params:
        max_deposit_period: "300s"
        min_deposit:
          - amount: "1000"
            denom: "sao" 
      voting_params:
        voting_period: "300s"
    mint:
      params:
        inflation_max: "0"
        inflation_min: "0"
        inflation_rate_change: "0"
        mint_denom: "sao"
validators:
- name: alice
  bonded: 100000000sao
