// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sao/did/past_seeds.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PastSeeds struct {
	Did   string   `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Seeds []string `protobuf:"bytes,2,rep,name=seeds,proto3" json:"seeds,omitempty"`
}

func (m *PastSeeds) Reset()         { *m = PastSeeds{} }
func (m *PastSeeds) String() string { return proto.CompactTextString(m) }
func (*PastSeeds) ProtoMessage()    {}
func (*PastSeeds) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e46c7c5cd2e88a, []int{0}
}
func (m *PastSeeds) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PastSeeds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PastSeeds.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PastSeeds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PastSeeds.Merge(m, src)
}
func (m *PastSeeds) XXX_Size() int {
	return m.Size()
}
func (m *PastSeeds) XXX_DiscardUnknown() {
	xxx_messageInfo_PastSeeds.DiscardUnknown(m)
}

var xxx_messageInfo_PastSeeds proto.InternalMessageInfo

func (m *PastSeeds) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *PastSeeds) GetSeeds() []string {
	if m != nil {
		return m.Seeds
	}
	return nil
}

func init() {
	proto.RegisterType((*PastSeeds)(nil), "saonetwork.sao.did.PastSeeds")
}

func init() { proto.RegisterFile("sao/did/past_seeds.proto", fileDescriptor_32e46c7c5cd2e88a) }

var fileDescriptor_32e46c7c5cd2e88a = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x4e, 0xcc, 0xd7,
	0x4f, 0xc9, 0x4c, 0xd1, 0x2f, 0x48, 0x2c, 0x2e, 0x89, 0x2f, 0x4e, 0x4d, 0x4d, 0x29, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2a, 0x4e, 0xcc, 0xcf, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca,
	0xd6, 0x2b, 0x4e, 0xcc, 0xd7, 0x4b, 0xc9, 0x4c, 0x51, 0x32, 0xe6, 0xe2, 0x0c, 0x48, 0x2c, 0x2e,
	0x09, 0x06, 0x29, 0x13, 0x12, 0xe0, 0x62, 0x4e, 0xc9, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xc1, 0x26, 0x48, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x06,
	0x41, 0x38, 0x4e, 0xf6, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c,
	0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xa5, 0x9a,
	0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x1f, 0x9c, 0x98, 0xef, 0x07, 0xb1,
	0x4d, 0x1f, 0xe4, 0xa4, 0x0a, 0xb0, 0xa3, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0x0e,
	0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x6d, 0x24, 0xb1, 0xac, 0x00, 0x00, 0x00,
}

func (m *PastSeeds) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PastSeeds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PastSeeds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Seeds) > 0 {
		for iNdEx := len(m.Seeds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Seeds[iNdEx])
			copy(dAtA[i:], m.Seeds[iNdEx])
			i = encodeVarintPastSeeds(dAtA, i, uint64(len(m.Seeds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintPastSeeds(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPastSeeds(dAtA []byte, offset int, v uint64) int {
	offset -= sovPastSeeds(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PastSeeds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovPastSeeds(uint64(l))
	}
	if len(m.Seeds) > 0 {
		for _, s := range m.Seeds {
			l = len(s)
			n += 1 + l + sovPastSeeds(uint64(l))
		}
	}
	return n
}

func sovPastSeeds(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPastSeeds(x uint64) (n int) {
	return sovPastSeeds(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PastSeeds) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPastSeeds
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PastSeeds: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PastSeeds: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPastSeeds
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPastSeeds
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPastSeeds
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seeds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPastSeeds
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPastSeeds
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPastSeeds
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seeds = append(m.Seeds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPastSeeds(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPastSeeds
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPastSeeds(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPastSeeds
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPastSeeds
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPastSeeds
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPastSeeds
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPastSeeds
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPastSeeds
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPastSeeds        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPastSeeds          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPastSeeds = fmt.Errorf("proto: unexpected end of group")
)
