// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sao/loan/loan_pool.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LoanPool struct {
	Total      types.DecCoin                          `protobuf:"bytes,1,opt,name=total,proto3" json:"total"`
	Loanable   types.Coin                             `protobuf:"bytes,2,opt,name=loanable,proto3" json:"loanable"`
	TotalBonds github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=totalBonds,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"totalBonds"`
}

func (m *LoanPool) Reset()         { *m = LoanPool{} }
func (m *LoanPool) String() string { return proto.CompactTextString(m) }
func (*LoanPool) ProtoMessage()    {}
func (*LoanPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e126dc3375a7678, []int{0}
}
func (m *LoanPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoanPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoanPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoanPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanPool.Merge(m, src)
}
func (m *LoanPool) XXX_Size() int {
	return m.Size()
}
func (m *LoanPool) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanPool.DiscardUnknown(m)
}

var xxx_messageInfo_LoanPool proto.InternalMessageInfo

func (m *LoanPool) GetTotal() types.DecCoin {
	if m != nil {
		return m.Total
	}
	return types.DecCoin{}
}

func (m *LoanPool) GetLoanable() types.Coin {
	if m != nil {
		return m.Loanable
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*LoanPool)(nil), "saonetwork.sao.loan.LoanPool")
}

func init() { proto.RegisterFile("sao/loan/loan_pool.proto", fileDescriptor_1e126dc3375a7678) }

var fileDescriptor_1e126dc3375a7678 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x33, 0xdf, 0xa7, 0x52, 0xc7, 0x5d, 0x74, 0x91, 0x16, 0x99, 0x16, 0x17, 0xd2, 0x4d,
	0x67, 0xa8, 0x6e, 0x04, 0x5d, 0x48, 0xec, 0x52, 0x44, 0xea, 0x4e, 0x84, 0x32, 0x49, 0x87, 0x18,
	0x9a, 0xce, 0x09, 0x9d, 0xf1, 0xef, 0x2e, 0xbc, 0x18, 0x2f, 0xa2, 0xcb, 0xe2, 0x4a, 0x5c, 0x54,
	0x49, 0x6e, 0x44, 0xe6, 0x07, 0xc9, 0xc2, 0x4d, 0x32, 0xc3, 0x7b, 0x9e, 0x67, 0x0e, 0xe7, 0xe0,
	0x48, 0x71, 0x60, 0x05, 0x70, 0x69, 0x3f, 0x93, 0x12, 0xa0, 0xa0, 0xe5, 0x02, 0x34, 0x84, 0xbb,
	0x8a, 0x83, 0x14, 0xfa, 0x09, 0x16, 0x33, 0xaa, 0x38, 0x50, 0x93, 0x77, 0xf6, 0x32, 0xc8, 0xc0,
	0xe6, 0xcc, 0x9c, 0x5c, 0x69, 0x87, 0xa4, 0xa0, 0xe6, 0xa0, 0x58, 0xc2, 0x95, 0x60, 0x8f, 0xc3,
	0x44, 0x68, 0x3e, 0x64, 0x29, 0xe4, 0xd2, 0xe7, 0x6d, 0x97, 0x4f, 0x1c, 0xe8, 0x2e, 0x2e, 0x3a,
	0xf8, 0x42, 0xb8, 0x75, 0x09, 0x5c, 0x5e, 0x03, 0x14, 0xe1, 0x09, 0xde, 0xd4, 0xa0, 0x79, 0x11,
	0xa1, 0x1e, 0xea, 0xef, 0x1c, 0xed, 0x53, 0x5f, 0x6a, 0xbc, 0xd4, 0x7b, 0xe9, 0x48, 0xa4, 0x17,
	0x90, 0xcb, 0x78, 0x63, 0xb9, 0xee, 0x06, 0x63, 0x07, 0x84, 0xa7, 0xb8, 0x65, 0xfa, 0xe3, 0x49,
	0x21, 0xa2, 0x7f, 0x16, 0x6e, 0xff, 0x09, 0x37, 0xc8, 0x5f, 0x20, 0xbc, 0xc3, 0xd8, 0x5a, 0x62,
	0x90, 0x53, 0x15, 0xfd, 0xef, 0xa1, 0xfe, 0x76, 0x7c, 0x66, 0x6a, 0x3e, 0xd7, 0xdd, 0xc3, 0x2c,
	0xd7, 0xf7, 0x0f, 0x09, 0x4d, 0x61, 0xee, 0x1b, 0xf7, 0xbf, 0x81, 0x9a, 0xce, 0x98, 0x7e, 0x29,
	0x85, 0x32, 0x1d, 0xbd, 0xbf, 0x0d, 0xb0, 0x7f, 0x6f, 0x24, 0xd2, 0x71, 0xc3, 0x17, 0x9f, 0x2f,
	0x2b, 0x82, 0x56, 0x15, 0x41, 0xdf, 0x15, 0x41, 0xaf, 0x35, 0x09, 0x56, 0x35, 0x09, 0x3e, 0x6a,
	0x12, 0xdc, 0x36, 0xdd, 0x37, 0x1c, 0xae, 0xdc, 0xb0, 0x99, 0xd9, 0xc8, 0xb3, 0xdb, 0x89, 0xf5,
	0x27, 0x5b, 0x76, 0x54, 0xc7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0x12, 0xe0, 0x6f, 0xac,
	0x01, 0x00, 0x00,
}

func (m *LoanPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoanPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoanPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalBonds.Size()
		i -= size
		if _, err := m.TotalBonds.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLoanPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Loanable.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLoanPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Total.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLoanPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintLoanPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovLoanPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LoanPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Total.Size()
	n += 1 + l + sovLoanPool(uint64(l))
	l = m.Loanable.Size()
	n += 1 + l + sovLoanPool(uint64(l))
	l = m.TotalBonds.Size()
	n += 1 + l + sovLoanPool(uint64(l))
	return n
}

func sovLoanPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLoanPool(x uint64) (n int) {
	return sovLoanPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LoanPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLoanPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoanPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoanPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoanPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLoanPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLoanPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Total.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Loanable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoanPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLoanPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLoanPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Loanable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBonds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoanPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoanPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoanPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalBonds.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLoanPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLoanPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLoanPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLoanPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLoanPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLoanPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLoanPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLoanPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLoanPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLoanPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLoanPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLoanPool = fmt.Errorf("proto: unexpected end of group")
)
