// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sao/node/pledge_debt.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PledgeDebt struct {
	Sp   string     `protobuf:"bytes,1,opt,name=sp,proto3" json:"sp,omitempty"`
	Debt types.Coin `protobuf:"bytes,2,opt,name=debt,proto3" json:"debt"`
}

func (m *PledgeDebt) Reset()         { *m = PledgeDebt{} }
func (m *PledgeDebt) String() string { return proto.CompactTextString(m) }
func (*PledgeDebt) ProtoMessage()    {}
func (*PledgeDebt) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7080da7c65ec51d, []int{0}
}
func (m *PledgeDebt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PledgeDebt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PledgeDebt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PledgeDebt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PledgeDebt.Merge(m, src)
}
func (m *PledgeDebt) XXX_Size() int {
	return m.Size()
}
func (m *PledgeDebt) XXX_DiscardUnknown() {
	xxx_messageInfo_PledgeDebt.DiscardUnknown(m)
}

var xxx_messageInfo_PledgeDebt proto.InternalMessageInfo

func (m *PledgeDebt) GetSp() string {
	if m != nil {
		return m.Sp
	}
	return ""
}

func (m *PledgeDebt) GetDebt() types.Coin {
	if m != nil {
		return m.Debt
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*PledgeDebt)(nil), "saonetwork.sao.node.PledgeDebt")
}

func init() { proto.RegisterFile("sao/node/pledge_debt.proto", fileDescriptor_b7080da7c65ec51d) }

var fileDescriptor_b7080da7c65ec51d = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8f, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0xe3, 0xa8, 0x42, 0xc2, 0x48, 0x0c, 0x81, 0xa1, 0x64, 0x30, 0x15, 0x03, 0xea, 0xe4,
	0x53, 0xe9, 0x0b, 0xa0, 0xc2, 0x8c, 0xa0, 0x6c, 0x2c, 0xc8, 0x4e, 0x4e, 0x21, 0x82, 0xe6, 0xac,
	0x9e, 0xf9, 0xf7, 0x16, 0x3c, 0x56, 0xc7, 0x8c, 0x4c, 0x08, 0x25, 0x2f, 0x82, 0x6c, 0xb3, 0x59,
	0xfa, 0x7d, 0xfa, 0x7c, 0x9f, 0x2c, 0xd9, 0x10, 0x74, 0x54, 0x23, 0xb8, 0x17, 0xac, 0x1b, 0x7c,
	0xac, 0xd1, 0x7a, 0xed, 0xb6, 0xe4, 0xa9, 0x38, 0x62, 0x43, 0x1d, 0xfa, 0x77, 0xda, 0x3e, 0x6b,
	0x36, 0xa4, 0x03, 0x56, 0x1e, 0x37, 0xd4, 0x50, 0xdc, 0x21, 0xbc, 0x12, 0x5a, 0xaa, 0x8a, 0x78,
	0x43, 0x0c, 0xd6, 0x30, 0xc2, 0xdb, 0xc2, 0xa2, 0x37, 0x0b, 0xa8, 0xa8, 0xed, 0xd2, 0x7e, 0x76,
	0x27, 0xe5, 0x6d, 0xf4, 0x5f, 0xa3, 0xf5, 0xc5, 0xa1, 0xcc, 0xd9, 0x4d, 0xc5, 0x4c, 0xcc, 0xf7,
	0xd7, 0x39, 0xbb, 0x62, 0x29, 0x27, 0xe1, 0xdb, 0x69, 0x3e, 0x13, 0xf3, 0x83, 0x8b, 0x13, 0x9d,
	0x64, 0x3a, 0xc8, 0xf4, 0xbf, 0x4c, 0x5f, 0x51, 0xdb, 0xad, 0x26, 0xbb, 0x9f, 0xd3, 0x6c, 0x1d,
	0xe1, 0xd5, 0xe5, 0x6e, 0x50, 0xa2, 0x1f, 0x94, 0xf8, 0x1d, 0x94, 0xf8, 0x1a, 0x55, 0xd6, 0x8f,
	0x2a, 0xfb, 0x1e, 0x55, 0xf6, 0x70, 0xde, 0xb4, 0xfe, 0xe9, 0xd5, 0xea, 0x8a, 0x36, 0x70, 0x6f,
	0xe8, 0x26, 0x25, 0x40, 0x28, 0xfd, 0x48, 0xad, 0xfe, 0xd3, 0x21, 0xdb, 0xbd, 0x78, 0xdb, 0xf2,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0xce, 0xde, 0xdf, 0x55, 0x04, 0x01, 0x00, 0x00,
}

func (m *PledgeDebt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PledgeDebt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PledgeDebt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Debt.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPledgeDebt(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Sp) > 0 {
		i -= len(m.Sp)
		copy(dAtA[i:], m.Sp)
		i = encodeVarintPledgeDebt(dAtA, i, uint64(len(m.Sp)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPledgeDebt(dAtA []byte, offset int, v uint64) int {
	offset -= sovPledgeDebt(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PledgeDebt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sp)
	if l > 0 {
		n += 1 + l + sovPledgeDebt(uint64(l))
	}
	l = m.Debt.Size()
	n += 1 + l + sovPledgeDebt(uint64(l))
	return n
}

func sovPledgeDebt(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPledgeDebt(x uint64) (n int) {
	return sovPledgeDebt(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PledgeDebt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPledgeDebt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PledgeDebt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PledgeDebt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPledgeDebt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPledgeDebt
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPledgeDebt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Debt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPledgeDebt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPledgeDebt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPledgeDebt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Debt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPledgeDebt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPledgeDebt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPledgeDebt(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPledgeDebt
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPledgeDebt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPledgeDebt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPledgeDebt
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPledgeDebt
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPledgeDebt
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPledgeDebt        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPledgeDebt          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPledgeDebt = fmt.Errorf("proto: unexpected end of group")
)
